### ISSUE TITLE
Not Work!

### ISSUE THREAD

**Issue by yysofiyan** [tuhin1729/Bot#1]
![Screen Shot 2020-05-23 at 10 09 16 PM](https://user-images.githubusercontent.com/34052001/82733999-142b3600-9d42-11ea-8610-cdd04956d57a.png)

Solusiont?

Tested MacOS

**Comment by tuhin1729** [comment]
Type the following command:
             `cd Bot && git pull && python2 bot.py`

**Comment by kevin1One** [comment]
the same problem in Ubuntu 18.04.4 LTS; tried your solution it doesn't work.
